### ISSUE TITLE
Feature request: Prefix devices

### ISSUE THREAD

**Issue by normanmaurer** [grzegorz914/homebridge-melcloud-control#120]
I want to use the plugin on two different homebridge instances so I can give my daughter access to her AC. This is currently not possible as once you startup the second instance it will clash due a service that is already registered on the network with the same name. It would be nice if we could either override the name or have some sort of prefix we can configure.

**Comment by grzegorz914** [comment]
Can you post the crash log, I will look what I can do

**Comment by normanmaurer** [comment]
Here you go:

```
homebridge-mia    | [6/20/2024, 10:25:20 AM] Got SIGTERM, shutting down Homebridge...
homebridge-mia    | [6/20/2024, 10:25:20 AM] [Meross] Child bridge process ended
homebridge-mia    | [6/20/2024, 10:25:21 AM] [Meross] Process Ended. Code: null, Signal: SIGTERM
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] ---- Air Conditioner: Schlafzimmer Klima ----
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] Account: Klima
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] Indoor: MSZ-AP25VG
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] Serial: 2052109410
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] Firmware: 37000
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] Manufacturer: Mitsubishi
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] ----------------------------------
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] Air Conditioner, Schlafzimmer Klima, Power: OFF
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] Air Conditioner, Schlafzimmer Klima, Operation mode: AIR CONDITIONER OFF
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] Air Conditioner, Schlafzimmer Klima, Room temperature: 24°C
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] Air Conditioner, Schlafzimmer Klima, Target temperature: 20°C
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] Air Conditioner, Schlafzimmer Klima, Heating threshold temperature: 20°C
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] Air Conditioner, Schlafzimmer Klima, Cooling threshold temperature: 20°C
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] Air Conditioner, Schlafzimmer Klima, Fan speed mode: QUIET
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] Air Conditioner, Schlafzimmer Klima, Vane swing mode: AUTO
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] Air Conditioner, Schlafzimmer Klima, Temperature display unit: °C
homebridge-mia    | [6/20/2024, 10:25:21 AM] [melcloudcontrol] Air Conditioner, Schlafzimmer Klima, Lock physical controls: UNLOCKED
homebridge-mia    | [6/20/2024, 10:25:21 AM] Schlafzimmer Klima 3798 is running on port 42539.
homebridge-mia    | [6/20/2024, 10:25:21 AM] Please add [Schlafzimmer Klima 3798] manually in Home app. Setup Code: 032-45-154
homebridge-mia    | [6/20/2024, 10:25:21 AM] Error: Service name is already in use on the network
homebridge-mia    |     at Registry._onProbeComplete (/homebridge/node_modules/homebridge/node_modules/bonjour-hap/lib/Registry.js:108:27)
homebridge-mia    |     at Prober.done (/homebridge/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:67:10)
homebridge-mia    |     at Prober.onMDNSresponse (/homebridge/node_modules/homebridge/node_modules/bonjour-hap/lib/Prober.js:61:102)
homebridge-mia    |     at EventEmitter.emit (node:events:518:28)
homebridge-mia    |     at Socket.<anonymous> (/homebridge/node_modules/homebridge/node_modules/multicast-dns/index.js:49:43)
homebridge-mia    |     at Socket.emit (node:events:518:28)
homebridge-mia    |     at UDP.onMessage (node:dgram:942:8)
```

**Comment by grzegorz914** [comment]
Are You already try to add in MELCLoud service quest Access and use this credentials data on other instance?

**Comment by normanmaurer** [comment]
@grzegorz914 yes... Is this not possible ?

**Comment by grzegorz914** [comment]
This is possible but wil break all current paired account, i will prepare beta for test and publish for You, be patient.

**Comment by normanmaurer** [comment]
@grzegorz914 actually I can also just create a new guest account for that. Maybe its good enough to document this ?

**Comment by grzegorz914** [comment]
Please try 0.21.9-beta and let me know

**Comment by normanmaurer** [comment]
Do I need to do any changes in the config ?

**Comment by grzegorz914** [comment]
No need any changes just in other instance create account for quest with different name, and the all accessory need to be paired again in Home app

**Comment by normanmaurer** [comment]
@grzegorz914 yes! This works :)

**Comment by grzegorz914** [comment]
Nice, i will publish it today.

**Comment by grzegorz914** [comment]
1.0.0 released
