### ISSUE TITLE
After update i get some strange error

### ISSUE THREAD

**Issue by LMITAB** [grzegorz914/homebridge-melcloud-control#150]
After update i get some strange errors...

[9/5/2024, 10:25:45 AM] [melcloudcontrol] ----------------------------------
[9/5/2024, 10:25:45 AM] ReferenceError: displayType is not defined
    at MelCloudAtw.<anonymous> (/homebridge/node_modules/homebridge-melcloud-control/src/deviceatw.js:444:75)
    at MelCloudAtw.emit (node:events:519:28)
    at ImpulseGenerator.<anonymous> (/homebridge/node_modules/homebridge-melcloud-control/src/melcloudatw.js:430:22)

**Comment by grzegorz914** [comment]
Go to plugin settings, connect to melcloud, save config and restart plugin.

**Comment by grzegorz914** [comment]
fixed in 3.1.9
