### ISSUE TITLE
plugin generated a warning

### ISSUE THREAD

**Issue by alexor424** [grzegorz914/homebridge-melcloud-control#176]
This plugin generated a warning from the characteristic 'Rotation Speed': characteristic value expected valid finite number and received "undefined" (undefined). 

Error: 
    at RotationSpeed.Characteristic.characteristicWarning (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:3016:105)
    at RotationSpeed.Characteristic.validateUserInput (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2908:14)
    at RotationSpeed.Characteristic.updateValue (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2333:20)
    at HeaterCooler.Service.updateCharacteristic (/var/lib/homebridge/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:804:35)
    at MelCloudAta.<anonymous> (/var/lib/homebridge/node_modules/homebridge-melcloud-control/src/deviceata.js:372:95)
    at MelCloudAta.emit (node:events:518:28)
    at Timeout._onTimeout (/var/lib/homebridge/node_modules/homebridge-melcloud-control/src/melcloudata.js:438:18)
    at listOnTimeout (node:internal/timers:573:17)
    at processTimers (node:internal/timers:514:7)

**Comment by richardalow** [comment]
I get the same error every time I set the rotation speed to the maximum level, which corresponds to Auto.

**Comment by grzegorz914** [comment]
@alexor424 , @richardalow 

please post the debug log

**Comment by grzegorz914** [comment]
Fixed
