### ISSUE TITLE
ECODAN heat pump

### ISSUE THREAD

**Issue by baz18** [grzegorz914/homebridge-melcloud-control#18]
Hi, 
I configured the plugin but I get this error when restarting homebridge
[9/8/2022, 5:31:43 PM] [melcloudcontrol] Heat Pump Ecodan , debug Info: [object Object]
[9/8/2022, 5:31:43 PM] [melcloudcontrol] Heat Pump Ecodan , check info, ReferenceError: ddeviceInfo is not defined, check again in 60s.
[9/8/2022, 5:31:43 PM] TypeError: this.log is not a function
    at process.error (/usr/lib/node_modules/homebridge/src/logger.ts:139:10)
    at process.emit (node:events:513:28)
    at process.emit (/usr/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
/usr/lib/node_modules/homebridge/lib/logger.js:90
        this.log("error" /* ERROR */, message, ...parameters);
             ^

TypeError: this.log is not a function
    at process.error (/usr/lib/node_modules/homebridge/src/logger.ts:139:10)
    at process.emit (node:events:525:35)
    at process.emit (/usr/lib/node_modules/homebridge/node_modules/source-map-support/source-map-support.js:516:21)
    at process._fatalException (node:internal/process/execution:167:25)

*********
debug log attached

thanks in advance for your help
Paolo

[log.zip](https://github.com/grzegorz914/homebridge-melcloud-control/files/9528468/log.zip)

**Comment by grzegorz914** [comment]
this is already fixed
