### ISSUE TITLE
Error making Homebridge shutdown

### ISSUE THREAD

**Issue by flavdessertine** [grzegorz914/homebridge-melcloud-control#59]
I have the following error recurently:
```
TypeError: Cannot read properties of undefined (reading 'updateCharacteristic')
    at MelCloudAtw.<anonymous> (/var/lib/homebridge/node_modules/homebridge-melcloud-control/src/melclouddevice.js:726:42)
    at MelCloudAtw.emit (node:events:514:28)
    at MelCloudAtw.<anonymous> (/var/lib/homebridge/node_modules/homebridge-melcloud-control/src/melcloudatw.js:534:22)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
```

It makes homebridge shutdown: 
`Got SIGTERM, shutting down Homebridge...`

**Comment by grzegorz914** [comment]
For prevent shutdown HB in future please run this plugin as child bridge.
