### ISSUE TITLE
Fan speed increments are incorrect in my air conditioner model

### ISSUE THREAD

**Issue by CyberMrProper** [grzegorz914/homebridge-melcloud-control#6]
These are the params coming in the API:

"ModelSupportsFanSpeed": true,
"HasAutomaticFanSpeed": true,
"NumberOfFanSpeeds": 3,

and  the current HK fan speed steps:
- 0: OFF
- 1: Min
- 2: Med
- 3: Max
- 4: — Does not exist in my AA model, should not be there 
- 5: — Does not exist in my AA model, should not be there 
- 6: Auto

**Comment by grzegorz914** [comment]
Are you sure 6 Is Auto, can you post the debug log if fan is in Auto mode?

**Comment by grzegorz914** [comment]
Please try 0.2.9-Betätigen and let me know

**Comment by CyberMrProper** [comment]
I will test it when I’m back home. No, I was mentioning 6 just to list all the steps in the slides (not the actual value for fan in auto). As of yesterday, when I set the fan at full speed, it set it to auto, so your logic is ok in that front. I think the only fix in here is the amount of fan speed the device supports .

**Comment by grzegorz914** [comment]
Ok, then I think the auto from your union will report 0

**Comment by CyberMrProper** [comment]
Yes, it's 0 for auto.

Speed 1
"FanSpeed": 1,

Speed 2
"FanSpeed": 2,

Speed 3
"FanSpeed": 3,

AUTO
"FanSpeed": 0,

I tested your beta, and AUTO (maximum position in HK slider) doesn't seem to work (see error below). As per the speeds, the invalid slider speed options (4 and 5) are gone now and looks ok.

[7/4/2022, 6:51:17 PM] [melcloudcontrol] Air Conditioner: Aire, Set fan speed mode: AUTO
[7/4/2022, 6:51:17 PM] [homebridge-melcloud-control] Error: 
    at RotationSpeed.Characteristic.characteristicWarning (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2142:105)
    at RotationSpeed.Characteristic.validateUserInput (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:2030:14)
    at RotationSpeed.Characteristic.updateValue (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Characteristic.ts:1457:20)
    at HeaterCooler.Service.updateCharacteristic (/usr/local/lib/node_modules/homebridge/node_modules/hap-nodejs/src/lib/Service.ts:481:35)
    at MELCLOUDCLIENTDEVICE.<anonymous> (/usr/local/lib/node_modules/homebridge-melcloud-control/index.js:301:81)
    at MELCLOUDCLIENTDEVICE.emit (node:events:527:28)
    at MELCLOUDCLIENTDEVICE.<anonymous> (/usr/local/lib/node_modules/homebridge-melcloud-control/src/melcloudclientdevice.js:201:22)
    at MELCLOUDCLIENTDEVICE.emit (node:events:527:28)
    at MELCLOUDCLIENTDEVICE.<anonymous> (/usr/local/lib/node_modules/homebridge-melcloud-control/src/melcloudclientdevice.js:150:22)
    at MELCLOUDCLIENTDEVICE.emit (node:events:527:28)

**Comment by grzegorz914** [comment]
Try beta.15 please

**Comment by CyberMrProper** [comment]
beta.15 works like a charm. Thanks!

**Comment by grzegorz914** [comment]
Thanks for testing, 0.2.9 released
