### ISSUE TITLE
Update makes the plugin go into a restart loop

### ISSUE THREAD

**Issue by JornDL** [grzegorz914/homebridge-melcloud-control#80]
Just updated to the latest version of the plugin 15-02-2024.

This makes the plugin go into a restart loop.

It states this error in status:

[2/15/2024, 2:54:34 PM] Homebridge v1.7.0 (HAP v0.11.1) (homebridge-melcloud-control) is running on port 45831.

/homebridge/node_modules/homebridge-melcloud-control/index.js:111
                                                                this.emit('error', error);
             ^
TypeError: this.emit is not a function
    at MQTTCLIENT.<anonymous> (/homebridge/node_modules/homebridge-melcloud-control/index.js:111:14)
    at MQTTCLIENT.emit (node:events:517:28)
    at MQTTCLIENT.connect (/homebridge/node_modules/homebridge-melcloud-control/src/mqtt.js:33:18)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[2/15/2024, 2:54:35 PM] [homebridge-melcloud-control] Child bridge process ended

**Comment by grzegorz914** [comment]
fixed
